development:
  adapter: postgresql
  encoding: unicode
  database: thedesignexchange_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: thedesignexchange_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: thedesignexchange_production
  pool: 5
