development:
  adapter: postgresql
  encoding: unicode
  database: thedesignexchange_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: thedesignexchange_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: thedesignexchange_production
  pool: 5
