development:
  adapter: sqlite3
  database: db/design_exchange_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/design_exchange_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/design_exchange_production.sqlite3
  pool: 5
  timeout: 5000
