require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CaseStudiesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # CaseStudy. As you add validations to CaseStudy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CaseStudiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all case_studies as @case_studies" do
      case_study = CaseStudy.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:case_studies)).to eq([case_study])
    end
  end

  describe "GET show" do
    it "assigns the requested case_study as @case_study" do
      case_study = CaseStudy.create! valid_attributes
      get :show, {:id => case_study.to_param}, valid_session
      expect(assigns(:case_study)).to eq(case_study)
    end
  end

  describe "GET new" do
    it "assigns a new case_study as @case_study" do
      get :new, {}, valid_session
      expect(assigns(:case_study)).to be_a_new(CaseStudy)
    end
  end

  describe "GET edit" do
    it "assigns the requested case_study as @case_study" do
      case_study = CaseStudy.create! valid_attributes
      get :edit, {:id => case_study.to_param}, valid_session
      expect(assigns(:case_study)).to eq(case_study)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CaseStudy" do
        expect {
          post :create, {:case_study => valid_attributes}, valid_session
        }.to change(CaseStudy, :count).by(1)
      end

      it "assigns a newly created case_study as @case_study" do
        post :create, {:case_study => valid_attributes}, valid_session
        expect(assigns(:case_study)).to be_a(CaseStudy)
        expect(assigns(:case_study)).to be_persisted
      end

      it "redirects to the created case_study" do
        post :create, {:case_study => valid_attributes}, valid_session
        expect(response).to redirect_to(CaseStudy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved case_study as @case_study" do
        post :create, {:case_study => invalid_attributes}, valid_session
        expect(assigns(:case_study)).to be_a_new(CaseStudy)
      end

      it "re-renders the 'new' template" do
        post :create, {:case_study => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested case_study" do
        case_study = CaseStudy.create! valid_attributes
        put :update, {:id => case_study.to_param, :case_study => new_attributes}, valid_session
        case_study.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested case_study as @case_study" do
        case_study = CaseStudy.create! valid_attributes
        put :update, {:id => case_study.to_param, :case_study => valid_attributes}, valid_session
        expect(assigns(:case_study)).to eq(case_study)
      end

      it "redirects to the case_study" do
        case_study = CaseStudy.create! valid_attributes
        put :update, {:id => case_study.to_param, :case_study => valid_attributes}, valid_session
        expect(response).to redirect_to(case_study)
      end
    end

    describe "with invalid params" do
      it "assigns the case_study as @case_study" do
        case_study = CaseStudy.create! valid_attributes
        put :update, {:id => case_study.to_param, :case_study => invalid_attributes}, valid_session
        expect(assigns(:case_study)).to eq(case_study)
      end

      it "re-renders the 'edit' template" do
        case_study = CaseStudy.create! valid_attributes
        put :update, {:id => case_study.to_param, :case_study => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested case_study" do
      case_study = CaseStudy.create! valid_attributes
      expect {
        delete :destroy, {:id => case_study.to_param}, valid_session
      }.to change(CaseStudy, :count).by(-1)
    end

    it "redirects to the case_studies list" do
      case_study = CaseStudy.create! valid_attributes
      delete :destroy, {:id => case_study.to_param}, valid_session
      expect(response).to redirect_to(case_studies_url)
    end
  end

end
